apiVersion: batch/v1
kind: Job
metadata:
  generateName: kcd-notify-config-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: kcd-notify
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "http://kcd-notify.demo:8080/api/notify?message=Synched"
      restartPolicy: Never
  backoffLimit: 2
